// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdp_packet_filterIpv4LpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type xdp_packet_filterRuleId struct {
	_        structs.HostLayout
	SubnetId uint32
	Proto    int32
	Port     uint32
}

// loadXdp_packet_filter returns the embedded CollectionSpec for xdp_packet_filter.
func loadXdp_packet_filter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_packet_filterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_packet_filter: %w", err)
	}

	return spec, err
}

// loadXdp_packet_filterObjects loads xdp_packet_filter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdp_packet_filterObjects
//	*xdp_packet_filterPrograms
//	*xdp_packet_filterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdp_packet_filterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_packet_filter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_packet_filterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_packet_filterSpecs struct {
	xdp_packet_filterProgramSpecs
	xdp_packet_filterMapSpecs
	xdp_packet_filterVariableSpecs
}

// xdp_packet_filterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_packet_filterProgramSpecs struct {
	XdpPacketFilter *ebpf.ProgramSpec `ebpf:"xdp_packet_filter"`
}

// xdp_packet_filterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_packet_filterMapSpecs struct {
	DefaultActionMap *ebpf.MapSpec `ebpf:"default_action_map"`
	RuleMap          *ebpf.MapSpec `ebpf:"rule_map"`
	SubnetMap        *ebpf.MapSpec `ebpf:"subnet_map"`
}

// xdp_packet_filterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_packet_filterVariableSpecs struct {
}

// xdp_packet_filterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdp_packet_filterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_packet_filterObjects struct {
	xdp_packet_filterPrograms
	xdp_packet_filterMaps
	xdp_packet_filterVariables
}

func (o *xdp_packet_filterObjects) Close() error {
	return _Xdp_packet_filterClose(
		&o.xdp_packet_filterPrograms,
		&o.xdp_packet_filterMaps,
	)
}

// xdp_packet_filterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdp_packet_filterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_packet_filterMaps struct {
	DefaultActionMap *ebpf.Map `ebpf:"default_action_map"`
	RuleMap          *ebpf.Map `ebpf:"rule_map"`
	SubnetMap        *ebpf.Map `ebpf:"subnet_map"`
}

func (m *xdp_packet_filterMaps) Close() error {
	return _Xdp_packet_filterClose(
		m.DefaultActionMap,
		m.RuleMap,
		m.SubnetMap,
	)
}

// xdp_packet_filterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdp_packet_filterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_packet_filterVariables struct {
}

// xdp_packet_filterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdp_packet_filterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_packet_filterPrograms struct {
	XdpPacketFilter *ebpf.Program `ebpf:"xdp_packet_filter"`
}

func (p *xdp_packet_filterPrograms) Close() error {
	return _Xdp_packet_filterClose(
		p.XdpPacketFilter,
	)
}

func _Xdp_packet_filterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_packet_filter_bpfel.o
var _Xdp_packet_filterBytes []byte
